/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "messaging.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(msg_query, msg_query, AUTO)


PB_BIND(msg_reply, msg_reply, AUTO)


PB_BIND(msg_set_voltage, msg_set_voltage, AUTO)


PB_BIND(msg_set_timebase, msg_set_timebase, AUTO)


PB_BIND(msg_set_trigger, msg_set_trigger, AUTO)


PB_BIND(UnionMessage, UnionMessage, AUTO)



